apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: jenkins-instance
