apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance-service
spec:
  type: NodePort
  ports:
    - port: 8081  # Servis portu
      targetPort: 5050  # Tomcat portu
      nodePort: 30000  # Dışarıya açılacak port
  selector:
    app: jenkins-instance
