apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance-service
spec:
  selector:
    app: jenkins-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
